### PR TITLE
Updated version of the bz-parking-app

### PR DESCRIPTION
**Pull request by mwallnoefer**
Improved version of the **bz-parking-app** created by the two TFO BZ students Philipp Piovesan and Christian Liso.

Please merge!

### CODE REVIEW

**Comment by Piiit** [comment]
@mwallnoefer Hi, and thanks for this contribution also to the two students. It is very nice to see, that students improve our projects :-D


May I ask you to remove the node_modules you added?

Let me know if you have any question. In the meantime I will mark this PR as draft...

Cheers,
Peter

**Comment by mwallnoefer** [comment]
Hallo Peter,

habe dich nicht ganz verstanden, es ist nicht ganz leicht, nur über Text miteinander zu interagieren.

Meintest du diese Abhängigkeiten in der _package.json_ zu löschen und dann _node_modules_ zu leeren?:
```
    "tsc": "^1.20150623.0",
    "typescript": "^4.1.3"
```

Oder gar nur _node_modules_ zu leeren, so dass ihr es auf dem Server neu erzeugt?

**Comment by Piiit** [comment]
Hi @mwallnoefer , what I mean is to remove the node_modules folder completely and put it into a .gitignore file... 

Secondly, we still need to create a staging environment to test these changes properly, so that might be at the beginning of next year. 

Thanks again and merry xmas!

**Comment by mwallnoefer** [comment]
> Hi @mwallnoefer , what I mean is to remove the node_modules folder completely and put it into a .gitignore file...

done
> 
> Secondly, we still need to create a staging environment to test these changes properly, so that might be at the beginning of next year.
> 
> Thanks again and merry xmas!

**Pull request merged**
